import Header from '@/components/layout/Header';
import { FilterProvider } from '@/context/FilterProvider';
import type { Metadata } from 'next';
import { ThemeProvider } from 'next-themes';
import { Noto_Sans } from 'next/font/google';
import './globals.css';

const notoSans = Noto_Sans({
  variable: '--font-notosans',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Browser Extensions Manager UI',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={`${notoSans.variable} antialiased min-h-screen px-4 pb-16 mt-6 bg-linear-(--light-gradient) dark:bg-linear-(--dark-gradient) xs:mx-auto xs:px-0 xs:max-w-xs sm:max-w-sm md:max-w-md lg:mt-10 lg:max-w-lg xl:max-w-xl`}
      >
        <ThemeProvider>
          <FilterProvider>
            <Header />
            {children}
          </FilterProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
